# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: order_service.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'order_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13order_service.proto\x12\x0corderservice\"#\n\x05Order\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0e\n\x06status\x18\x02 \x01(\t\"\x14\n\x12\x46\x65tchOrdersRequest\":\n\x13\x46\x65tchOrdersResponse\x12#\n\x06orders\x18\x01 \x03(\x0b\x32\x13.orderservice.Order2b\n\x0cOrderService\x12R\n\x0b\x46\x65tchOrders\x12 .orderservice.FetchOrdersRequest\x1a!.orderservice.FetchOrdersResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'order_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ORDER']._serialized_start=37
  _globals['_ORDER']._serialized_end=72
  _globals['_FETCHORDERSREQUEST']._serialized_start=74
  _globals['_FETCHORDERSREQUEST']._serialized_end=94
  _globals['_FETCHORDERSRESPONSE']._serialized_start=96
  _globals['_FETCHORDERSRESPONSE']._serialized_end=154
  _globals['_ORDERSERVICE']._serialized_start=156
  _globals['_ORDERSERVICE']._serialized_end=254
# @@protoc_insertion_point(module_scope)
