# k8s/server-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-server
  template:
    metadata:
      labels:
        app: order-server
    spec:
      containers:
      - name: server
        image: gruposd/order-server:latest
        ports:
        - containerPort: 50052
---
apiVersion: v1
kind: Service
metadata:
  name: order-server-service
spec:
  selector:
    app: order-server
  ports:
    - protocol: TCP
      port: 50052
      targetPort: 50052
  type: ClusterIP