# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: fetch.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'fetch.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x66\x65tch.proto\"\x1d\n\x0c\x46\x65tchRequest\x12\r\n\x05query\x18\x01 \x01(\t\"\x1f\n\rFetchResponse\x12\x0e\n\x06result\x18\x01 \x01(\t26\n\x0c\x46\x65tchService\x12&\n\x05\x46\x65tch\x12\r.FetchRequest\x1a\x0e.FetchResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'fetch_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_FETCHREQUEST']._serialized_start=15
  _globals['_FETCHREQUEST']._serialized_end=44
  _globals['_FETCHRESPONSE']._serialized_start=46
  _globals['_FETCHRESPONSE']._serialized_end=77
  _globals['_FETCHSERVICE']._serialized_start=79
  _globals['_FETCHSERVICE']._serialized_end=133
# @@protoc_insertion_point(module_scope)
