apiVersion: v1
kind: Service
metadata:
  name: virtual-worker
  namespace: argocd  # Specify the namespace
  labels:
    app: virtual-worker
spec:
  selector:
    app: virtual-worker
  ports:
    - protocol: TCP
      port: 50051
      targetPort: 50051
