apiVersion: apps/v1
kind: Deployment
metadata:
  name: virtual-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: virtual-worker
  template:
    metadata:
      labels:
        app: virtual-worker
    spec:
      nodeSelector:
        "kubernetes.io/os": linux
      containers:
      - name: virtual-worker
        image: grupo5sd/virtual_worker:latest
        env:
        - name: GRPC_SERVER_ADDRESS  # Updated for clarity
          value: "order-service:50051"
        - name: ORDERS_PER_HOUR
          value: "5"
        resources:
          requests:
            cpu: 100m
            memory: 64Mi
          limits:
            cpu: 250m
            memory: 128Mi
        livenessProbe:  # Add liveness probe
          tcpSocket:
            port: 50051
          initialDelaySeconds: 5
          periodSeconds: 10
        readinessProbe:  # Add readiness probe
          tcpSocket:
            port: 50051
          initialDelaySeconds: 5
          periodSeconds: 10
