apiVersion: apps/v1
kind: Deployment
metadata:
  name: virtual-customer
  namespace: argocd
  labels:
    app: virtual-customer
spec:
  replicas: 3
  selector:
    matchLabels:
      app: virtual-customer
  template:
    metadata:
      labels:
        app: virtual-customer
    spec:
      nodeSelector:
        "kubernetes.io/os": linux
      initContainers:
      - name: wait-for-virtual-worker
        image: busybox:latest
        command: ['sh', '-c', 'until nc -zv virtual-worker 50051; do echo "Waiting for virtual-worker..."; sleep 2; done;']
        resources:
          requests:
            cpu: 10m
            memory: 10Mi
          limits:
            cpu: 50m
            memory: 20Mi
      containers:
      - name: virtual-customer
        image: grupo5sd/virtual_customer:latest
        imagePullPolicy: Always
        env:
        - name: ORDER_SERVICE_URL
          value: "virtual-worker:50051"
        resources:
          requests:
            cpu: 100m
            memory: 64Mi
          limits:
            cpu: 250m
            memory: 128Mi
