name: Build and Push Docker Image

on:
  push:
    branches:
      - main
      - pipeline

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the source code
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      # Log in to DockerHub (DockerHub credentials should be configured in GitHub Secrets)
      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build and Tag Docker Images
      - name: Build and Tag Docker Image
        run: |
          docker build -t grupo5sd/virtual_worker:latest -f src/virtual-worker/Dockerfile src/virtual-worker
          docker build -t grupo5sd/virtual_customer:latest -f src/virtual-customer/Dockerfile src/virtual-customer

      # Push Docker Images to DockerHub
      - name: Push Docker Image
        run: |
          docker push grupo5sd/virtual_worker:latest
          docker push grupo5sd/virtual_customer:latest