name: Build and Push Docker Image

on:
  push:
    branches:
      - main
      - pipeline

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checkout do código fonte
    - name: Checkout code
      uses: actions/checkout@v2

    # Configura o Docker
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    # Logar no DockerHub (DockerHub credentials devem ser configuradas nos Secrets do GitHub)
    - name: Log in to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Construir a imagem Docker e tagueá-la
    - name: Build and Tag Docker Image
      run: |
        docker build -t grupo5sd/client:latest -f src/virtual-worker/client/Dockerfile .
        docker build -t grupo5sd/server:latest -f src/virtual-worker/server/Dockerfile .

    # Empurrar a imagem para o DockerHub
    - name: Push Docker Image
      run: |
        docker push grupo5sd/client:latest
        docker push grupo5sd/server:latest

       
       

  