name: Build and Push Docker Image

on:
  push:
    branches:
      - main
      - pipeline

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checkout do código fonte
    - name: Checkout code
      uses: actions/checkout@v3

    # Configura o Docker
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    # Logar no DockerHub
    - name: Log in to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Construir e Push a imagem Docker para o Client
    - name: Build and Push Docker Image - Client
      uses: docker/build-push-action@v3
      with:
        context: src/virtual-worker/client
        file: src/virtual-worker/client/Dockerfile
        push: true
        tags: grupo5sd/client:${{ github.sha }}

    # Construir e Push a imagem Docker para o Server
    - name: Build and Push Docker Image - Server
      uses: docker/build-push-action@v3
      with:
        context: src/virtual-worker/server
        file: src/virtual-worker/server/Dockerfile
        push: true
        tags: grupo5sd/server:${{ github.sha }}